### ISSUE TITLE
Incorrect detection of builtin functions for clang.

### ISSUE THREAD

**Issue by niedzwiecki-dawid** [picolibc/picolibc#805]
Build system detects builtin functions incorrectly for clang:
```
  -
    kind: "try_compile-v1"
    backtrace:
      - "/mnt/host/source/src/third_party/zephyr/picolibc/cmake/picolibc.cmake:151 (try_compile)"
      - "/mnt/host/source/src/third_party/zephyr/picolibc/CMakeLists.txt:177 (picolibc_flag)"
    directories:
      source: "/mnt/host/source/src/platform/ec/twister-out/native_sim/tests/lib/cpp/cxx/cpp.main.picolibc/modules/picolibc/CMakeFiles/CMakeTmp"
      binary: "/mnt/host/source/src/platform/ec/twister-out/native_sim/tests/lib/cpp/cxx/cpp.main.picolibc/modules/picolibc/CMakeFiles/CMakeTmp"
    cmakeVariables:
      CMAKE_CXX_COMPILER_TARGET: "x86_64-pc-linux-gnu"
      CMAKE_C_COMPILER_TARGET: "x86_64-pc-linux-gnu"
      CMAKE_C_FLAGS: ""
      CMAKE_C_FLAGS_DEBUG: "-g"
      CMAKE_EXE_LINKER_FLAGS: ""
      CMAKE_MODULE_PATH: "/mnt/host/source/src/third_party/zephyr/main/cmake/modules"
    buildResult:
      variable: "_HAVE_BUILTIN_ISINFL"
      cached: true
      stdout: |
        Change Dir: /mnt/host/source/src/platform/ec/twister-out/native_sim/tests/lib/cpp/cxx/cpp.main.picolibc/modules/picolibc/CMakeFiles/CMakeTmp
        
        Run Build Command(s):/usr/bin/ninja -v cmTC_5e6a5 && [1/2] /usr/bin/x86_64-pc-linux-gnu-clang --target=x86_64-pc-linux-gnu   -Werror=missing-declarations -Werror=unknown-attributes -Werror=attributes -Werror=unsupported-floating-point-opt -Werror=ignored-optimization-argument -Werror=attribute-optimize -Wno-unused-command-line-argument -MD -MT CMakeFiles/cmTC_5e6a5.dir/have-builtin-isinfl.c.obj -MF CMakeFiles/cmTC_5e6a5.dir/have-builtin-isinfl.c.obj.d -o CMakeFiles/cmTC_5e6a5.dir/have-builtin-isinfl.c.obj -c /mnt/host/source/src/third_party/zephyr/picolibc/cmake/have-builtin-isinfl.c
        /mnt/host/source/src/third_party/zephyr/picolibc/cmake/have-builtin-isinfl.c:2:29: warning: use of unknown builtin '__builtin_isinfl' [-Wimplicit-function-declaration]
            2 | int main(void) { return foo(__builtin_isinfl((long double)42)); }
              |                             ^
        1 warning generated.
        [2/2] : && /usr/bin/cmake -E rm -f libcmTC_5e6a5.a && /usr/bin/llvm-ar qc libcmTC_5e6a5.a  CMakeFiles/cmTC_5e6a5.dir/have-builtin-isinfl.c.obj && /usr/bin/llvm-ranlib libcmTC_5e6a5.a && :
        
      exitCode: 0
```

Despite the fact bulitin function is unknown, the exitCode is still 0.

Adding `-Werror=implicit-function-declaration` to the [_picolibc_supported_compile_options](https://github.com/picolibc/picolibc/blob/main/cmake/picolibc.cmake#L123) function solves the problem.
